#sdk: "/Users/robgalvin/.rvm/scripts/gems/ruby-1.9.3-p551/gems/rhodes-5.1.1"
sdkversion: "5.1.0"
name: "GeoTest"
version: 1.0
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator8.2"
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.geotest"
  BundleURLScheme: "geotest"
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
wp8:
  productid: "ee3b97c0-3d4c-0133-6f5c-2c87a3057736"
android:
#manifest_template: 'AndroidManifest.erb'
  version: "2.3.3"
# Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: "APP:I StrictMode:I DEBUG:I *:E"
  abis:
    - arm
    - x86
#sdk: "MC3000c50b (ARMV4I)"
#sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
wm: 
win32:
  deployqt: 1
  deploymsvc: 1
extensions:
  - rhoconnect-client
  - rho-javascript
  - json
rhobundle:
  exclude_items:
    - thumb.db
capabilities:
  - gps
